/***********************************************************************/
/*                                                                     */
/*  FILE        :porola.c                                              */
/*  DATE        :Wed, May 09, 2018                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX62N                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.52).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/

//#include "typedefine.h"
#include "iodefine.h"
#include "vect.h"
#include "motor.h"
#include "servo.h"
#include "rxpi.h"
#include "distance_measure.h"
#include "run_mode.h"
#include "release_ball.h"
#include "communicate_arduino.h"
#ifdef MAIN_POROLA_MODE

void get_free_ball();
void finish_mode();

void main(void)
{
	//initialize robot
	pattern = none;
	rx_state = STOP_;
	init_motor();
	initilize_linetrace();
	init_servo();
	init_ADC();
	init_UART();
	init_CMT();
	init_PORT_for_Arduino();
	init_horn();
	start_CMT0();
	start_ADC0(); //for linetrace
	start_ADC1(); //for distance sencer

	get_free_ball();

	while(1)
	{
		switch(pattern){

			case none:
				
			break;

			case waiting:
				
			break;

			case tracing:
				rprintf("tracing\r\n");
				start_linetrace();
			break;

			case set_start_pos:
				rprintf("set_start_pos\r\n");
				set_start_position();
			break;

			case set_second_pos:
				rprintf("set_second_pos\r\n");
				set_second_position();
			break;

			case searching:
				rprintf("searching\r\n");
				start_search();
			break;

			case second_lap_searching:
				rprintf("second_lap_searching\r\n");
				start_second_lap_search();
			break;

			case return_tracing:
				rprintf("return_tracing\r\n");
				start_return_linetrace();
			break;

			case blue:
				rprintf("blue\r\n");
				blue_act();
			break;

			case yellow:
				rprintf("yellow\r\n");
				yellow_act();
			break;

			case red:
				rprintf("red\r\n");
				red_act();
				if(rap_flag == 1){
					pattern = restart;
				}else{
					pattern = finish;
				}
				
			break;

			case restart:
				line_num = 0;
				reset_port_for_Arduino();
				pattern = tracing;
			break;

			case finish:
				finish_mode();
			break;
		}
	}
}

void get_free_ball()
{
	//first tracking
	traj_tracking(0.50, 0.0, 3.0);
	traj_tracking(0.0, -60.0, 3.0);
	traj_tracking(0.0, 60.0, 3.0);
	traj_tracking(0.30, 0.0, 2.0);

	pattern = tracing;
	//pattern = searching;
	//pattern = return_tracing;
}

void finish_mode()
{
	traj_tracking(-0.70, 0.0, 5.0);
	pattern = none;
	rx_state = STOP_REQ_;
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
#endif