/***********************************************************************/
/*                                                                     */
/*  FILE        :porola.c                                              */
/*  DATE        :Wed, May 09, 2018                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX62N                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.52).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/

//#include "typedefine.h"
#include "iodefine.h"
#include "vect.h"
#include "motor.h"
#include "servo.h"
#include "rxpi.h"
#include "distance_measure.h"
#include "run_mode.h"
#include "release_ball.h"
#ifdef MAIN_POROLA_MODE

void main(void)
{
	//init
	pattern = none;
	rx_state = STOP_;
	init_motor();
	init_servo();
	init_ADC();
	init_UART();
	init_CMT();
	init_PORT_for_Arduino();
	init_horn();

	start_CMT0();
	start_ADC0(); //for linetrace
	start_ADC1(); //for distance sencer

	//first tracking
	traj_tracking(0.50, 0.0, 3.0);
	traj_tracking(0.0, -60.0, 3.0);
	traj_tracking(0.0, 60.0, 3.0);
	traj_tracking(0.30, 0.0, 2.0);

	//start linetrace
	pattern = tracing;

	//start searching
	//pattern = searching;

	while(1)
	{
		switch(pattern){

			case none:
				
			break;

			case waiting:
				
			break;

			case tracing:
				rprintf("tracing\r\n");
				start_linetrace();
			break;

			case set_start_line_pos:
				rprintf("set_start_line_pos\r\n");
				set_start_pos();
			break;

			case searching:
				rprintf("searching\r\n");
				start_search();
			break;

			case return_tracing:
				rprintf("return_tracing\r\n");
				start_return_linetrace();
			break;

			case blue:
				rprintf("blue\r\n");
				blue_act();
			break;

			case yellow:
				rprintf("yellow\r\n");
				yellow_act();
			break;

			case red:
				rprintf("red\r\n");
				red_act();
				// todo:count rap and decide end or restart
				pattern = waiting;
			break;
		}
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
#endif